### ISSUE TITLE
Keyboard hide bottomsheet issue

### ISSUE THREAD

**Issue by mustafakibar** [michael-rapp/AndroidBottomSheet#11]
When I was use bottomsheet with my custom view I get issue. When bottomsheet visible then I focus on the edittext unfortunately keyboard hide bottomsheet. I was write setSoftInputMode but it doesn't work. Why?

```
            BottomSheet.Builder(context)
                    .setTitle("Deneme")
                    .setView(R.layout.add_suspect)
                    .create()
                    .apply {
                        setOnShowListener {
                            this.window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_HIDDEN or WindowManager.LayoutParams.SOFT_INPUT_ADJUST_PAN)
                        }
                        show()
                    }
```

**Comment by michael-rapp** [comment]
You code doesn't make sense to me. There isn't an `apply`-method in this library. Are you sure that you are actually using this library? It should become obvious when taking a look at the classes' imports.

**Comment by mustafakibar** [comment]
Sorry for little information. I'm use kotlin. So **this** keyword in `apply` represent` BottomSheet` dialog.

**Comment by michael-rapp** [comment]
Ok, I got it. I am not very familiar with Kotlin.

So your layout contains an EditText, right? What exactly do you want to achieve? Do want the keyboard to not show up? Or do you want the keyboard to be shown below the bottom sheet?

**Comment by mustafakibar** [comment]
Yes layout has edittext. When  `BottomSheet` dialog comes to visible then user interact the edittext. And the bottomsheet stays behind the keyboard after the keyboard is visible.  

But I added this: 

`this.window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_HIDDEN or WindowManager.LayoutParams.SOFT_INPUT_ADJUST_PAN)` in `onShowListener()` 

So bottomsheet dialog should be on the keyboard? But it's doesn't work.

**Comment by ashu-mkb** [comment]
@mustafakibar u got the solution? please help.

**Comment by MuhShalah007** [comment]
> 

I Want the keyboard to be shown below the bottom sheet please... How?
