### ISSUE TITLE
No cached version of com.github.michael-rapp:android-util:1.4.5 available for offline mode.

### ISSUE THREAD

**Issue by wu110011** [michael-rapp/AndroidBottomSheet#6]
The show error message below when I import this project into Android Studio 1.5.1.

Error:A problem occurred configuring project ':example'.

> A problem occurred configuring project ':library'.
> Could not resolve all dependencies for configuration ':library:_debugCompile'.
>       > Could not resolve com.github.michael-rapp:android-util:1.4.5.
>         Required by:
>             com.github.michael-rapp:library:1.1.1
>          > No cached version of com.github.michael-rapp:android-util:1.4.5 available for offline mode.

**Comment by michael-rapp** [comment]
"com.github.michael-rapp:android-util:1.4.5" refers to a library project, this library depends on (you can find it here: https://github.com/michael-rapp/AndroidUtil). It should automatically be downloaded by Gradle when building the project in Android Studio for the first time. It seems like no internet connection was available when you tried to build the project. In such case Gradle is run in "offline mode". You should try to build the project with an internet connection established. Once downloaded for the first time, downloading the dependency is not necessary anymore for subsequent builds.

**Comment by wu110011** [comment]
I try it,thanks.
