### ISSUE TITLE
about item listener

### ISSUE THREAD

**Issue by BigSnake1989** [michael-rapp/AndroidBottomSheet#8]
Hi Dear:
    i set setOnItemClickListener and setOnItemLongClickListener,when i Long click,setOnItemClickListener also responsive

**Comment by michael-rapp** [comment]
Hello,

it is standard Android behavior that both listeners are invoked. Please notice, that the listener for observing long-clicks is always invoked before the regular click listener. If your `OnItemLongClickListener` has handled the event and if you want to prevent the `OnItemClickListener` from being called afterwards, you can just return `true` as the listener's return value.

See here for further information: http://stackoverflow.com/questions/5428077/android-why-does-long-click-also-trigger-a-normal-click

**Comment by BigSnake1989** [comment]
but it don't close.

**Comment by michael-rapp** [comment]
If you want to close the `BottomSheet` when your `OnItemLongClickListener` is invoked, you have to call the `BottomSheet`'s `dismiss`-method inside the listener's `onItemClick`-method.
